export const input = '[data-testid="input"]';
export const circle = '[data-testid^="circle-"]';
export const addButton = '[data-testid="add-button"]';
export const addHeadButton = '[data-testid="add-head-button"]';
export const addTailButton = '[data-testid="add-tail-button"]';
export const addIndexButton = '[data-testid="add-index-button"]';
export const removeIndexButton = '[data-testid="remove-index-button"]';
export const inputIndex = '[data-testid="input-index"]';
export const clearButton = '[data-testid="clear-button"]';
